# This workflow will triage pull requests and respond on the
# PR if restricted files are modified in the pull request.


name: detect-changes

on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v23
        with:
          files: |
            rubric/rubric.json
            rubric/rubric.md

      - name: Run step if any of the listed files above change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
